### ISSUE TITLE
Question regarding success rates

### ISSUE THREAD

**Issue by mchivuku** [sparisi/pvr_habitat#1]
Hello @sparisi ,

I am currently working on replicating results from your paper with the intention to extend the work. 
I used the 'main' branch and downloaded the pretrained models provided using the github link. I was able to replicate the ground truth results for the Habitat dataset but having little trouble replicating results for - resnet50 models pretrained on ImageNet for embedding name - resnet50_l3 and resnet50_l4. I am running following commands:

## Generated Optimal trajectories for 5 scenes
python behavioral_cloning/save_opt_trajectories.py --env=HabitatImageNav-apartment_0
python behavioral_cloning/save_opt_trajectories.py --env=HabitatImageNav-frl_apartment_0
python behavioral_cloning/save_opt_trajectories.py --env=HabitatImageNav-room_0
python behavioral_cloning/save_opt_trajectories.py --env=HabitatImageNav-hotel_0
python behavioral_cloning/save_opt_trajectories.py --env=HabitatImageNav-office_0

# generated desired embeddings
python behavioral_cloning/save_embedded_obs.py --env=HabitatImageNav-apartment_0 --embedding_name=resnet50_l3 --source=pickle
python behavioral_cloning/save_embedded_obs.py --env=HabitatImageNav-frl_apartment_0 --embedding_name=resnet50_l3 --source=pickle
python behavioral_cloning/save_embedded_obs.py --env=HabitatImageNav-room_0 --embedding_name=resnet50_l3 --source=pickle
python behavioral_cloning/save_embedded_obs.py --env=HabitatImageNav-hotel_0 --embedding_name=resnet50_l3 --source=pickle
python behavioral_cloning/save_embedded_obs.py --env=HabitatImageNav-office_0 --embedding_name=resnet50_l3 --source=pickle

## running bc files - to train the policy network for 5 seeds
python main_bc_2.py --env=HabitatImageNav-apartment_0,HabitatImageNav-frl_apartment_0,HabitatImageNav-room_0,HabitatImageNav-hotel_0,HabitatImageNav-office_0 --embedding_name=resnet50_l3 --run_id=1

python main_bc_2.py --env=HabitatImageNav-apartment_0,HabitatImageNav-frl_apartment_0,HabitatImageNav-room_0,HabitatImageNav-hotel_0,HabitatImageNav-office_0 --embedding_name=resnet50_l3 --run_id=2

python main_bc_2.py --env=HabitatImageNav-apartment_0,HabitatImageNav-frl_apartment_0,HabitatImageNav-room_0,HabitatImageNav-hotel_0,HabitatImageNav-office_0 --embedding_name=resnet50_l3 --run_id=3

python main_bc_2.py --env=HabitatImageNav-apartment_0,HabitatImageNav-frl_apartment_0,HabitatImageNav-room_0,HabitatImageNav-hotel_0,HabitatImageNav-office_0 --embedding_name=resnet50_l3 --run_id=4

python main_bc_2.py --env=HabitatImageNav-apartment_0,HabitatImageNav-frl_apartment_0,HabitatImageNav-room_0,HabitatImageNav-hotel_0,HabitatImageNav-office_0 --embedding_name=resnet50_l3 --run_id=5

### computed the mean across five seeds for the last 6 policy updates as described in the paper - i am not able to get the same value as mentioned. Can you please let me know what I am doing wrong?

###I also tried testing the models by running following command again - model_test.py file

python main_test.py --from_env=HabitatImageNav-apartment_0,HabitatImageNav-frl_apartment_0,HabitatImageNav-room_0,HabitatImageNav-hotel_0,HabitatImageNav-office_0 --embedding_name=resnet50_l3  --to_env=HabitatImageNav-apartment_0

Thank you for the help!

**Comment by sparisi** [comment]
Hey, thanks for trying our code!
It seems that you did all the steps correctly, so I am not sure where the error could be.
How different the results are?

**Comment by mchivuku** [comment]
Hello Simone,
Thank you for the quick response. I am rerunning (repeating) the experiments to double check everything again (since i have got confirmation from you that my steps are correct). For resent50_l3 I got about 0.4 success rate which is very low compared to what was quoted in the paper. This is also the result during model testing on each of the 5 habitat scenes by running - main_test.py using the saved weights after running main_bc_2.py. I will keep you updated and will send you logs to make sure i am not doing something wrong. Thank you for your time and help.

**Comment by mchivuku** [comment]
Thank you Simone. I am sorry for the confusion, I was able to replicate the results after running for 5 seeds and taking an average on testing across 5 habitat scenes. Sorry about the delay in posting this message. Thank you for your time and help.
